pipeline {
    agent any

    stages {
        stage('Success') {
            steps {
                echo 'This stage will pass'
            }
        }

        stage('Failure') {
            steps {
                sh 'exit 1'
            }
        }

        stage('Never Runs') {
            steps {
                echo 'You will not see this'
            }
        }
    }
}

