apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
spec:
  containers:
  - name: test
    image: busybox
    command: ["sleep","3600"]
    volumeMounts:
    - name: testvol
      mountPath: /data
  volumes:
  - name: testvol
    hostPath:
      path: /var/log
