apiVersion: v1
kind: Pod
metadata:
  name: good-pod
spec:
  containers:
  - name: test
    image: busybox
    command: ["sleep","3600"]
    securityContext:
      runAsNonRoot: true
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
